# Generated by Django 5.0.4 on 2025-06-10 18:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaturityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст вопроса')),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Вес вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос цифровой зрелости',
                'verbose_name_plural': 'Вопросы цифровой зрелости',
            },
        ),
        migrations.CreateModel(
            name='DisciplineFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=128, verbose_name='Дисциплина')),
                ('knowledge_level', models.IntegerField(choices=[(1, 'Слабые знания'), (2, 'Средние знания'), (3, 'Хорошие знания')], default=2, verbose_name='Уровень знаний')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_feedbacks', to='finder.candidate', verbose_name='Кандидат')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_feedbacks', to='finder.hr', verbose_name='HR')),
            ],
            options={
                'verbose_name': 'Обратная связь по дисциплине',
                'verbose_name_plural': 'Обратные связи по дисциплинам',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CompanyMaturityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Ответ (0‑1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maturity_answers', to='finder.company', verbose_name='Компания')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.maturityquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ цифровой зрелости',
                'verbose_name_plural': 'Ответы цифровой зрелости',
                'unique_together': {('company', 'question')},
            },
        ),
    ]
