# Generated by Django 5.0.4 on 2025-06-10 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_maturityquestion_disciplinefeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='Какое-то резюме без названия', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='rank',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень владения'),
        ),
    ]
