version: '3.3'

services:
  web:
    build:
      context: ./finddotemployee
      dockerfile: Dockerfile
    command: gunicorn finddotemployee.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:15.13-bullseye
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=db
    ports:
      - 5432:5432
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 81:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
